server:
  port: 9003

spring:
  application:
    name: user-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/user_database
    username: root
    password: Kaven@45cr7
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

#spring:
#  application:
#    name: user-service
#
#  cloud:
#    config:
#      enabled: false
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/user_database
#    username: root
#    password: Kaven@45cr7
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
