server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/libraries/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#routes:
#  - id: user-service
#    uri: lb://USER-SERVICE
#    predicates:
#      - Path=/users/**
#  - id: department-service
#    uri: lb://DEPARTMENT-SERVICE
#    predicates:
#      - Path=/departments/**

#server:
#  port: 8060
#
#spring:
#  application:
#    name: api-gateway
#
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/
#
#  cloud:
#    gateway:
#      routes:
#        - id: department-service
#          uri: lb://department-service
#          predicates:
#            - Path=/departments/**
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
